#!/bin/bash -x
THISDIR=$PWD
git pull
SEARCH=""
if [ -n "$1" ]; then
	SEARCH="/$1/ "
fi
awk "$SEARCH"'{ print $1,$4,$5,$6 }' < switches.txt | while read sw ip class password;do
MYIP="$(ip ro get $ip|awk '/src/ { print $5 }')"
echo name: $sw ip: $ip myip: $MYIP class: $class
case "$class" in
	gs748tv5)
		class=gs724tv4
		;;
esac
case "$class" in
	gs724tv4)
		mkdir -p /srv/tftp/backup
		DESTFILE=backup/$sw.txt
		touch /srv/tftp/$DESTFILE
		chmod a+w /srv/tftp/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/}
		if [ "$(tail -n +10 /srv/tftp/$DESTFILE|md5sum)" != "$(tail -n +10 $THISDIR/backups/$sw.txt|md5sum)" ] && [ -s /srv/tftp/$DESTFILE ]; then
			mv /srv/tftp/$DESTFILE $THISDIR/backups/$sw.txt
			chmod go-w $THISDIR/backups/$sw.txt
			git add $THISDIR/backups/$sw.txt
		else
			rm /srv/tftp/$DESTFILE
		fi
		;;
	hp2530)
		mkdir -p /srv/tftp/backup
		DESTFILE=backup/$sw.txt
		touch /srv/tftp/$DESTFILE
		chmod a+w /srv/tftp/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/}
		if [ "$(tail -n +0 /srv/tftp/$DESTFILE|md5sum)" != "$(tail -n +0 $THISDIR/backups/$sw.txt|md5sum)" ] && [ -s /srv/tftp/$DESTFILE ]; then
			mv /srv/tftp/$DESTFILE $THISDIR/backups/$sw.txt
			chmod go-w $THISDIR/backups/$sw.txt
			git add $THISDIR/backups/$sw.txt
		else
			rm /srv/tftp/$DESTFILE
		fi
		;;
	lgs318p)
		mkdir -p /srv/tftp/backup
		DESTFILE=backup/$sw.txt
		touch /srv/tftp/$DESTFILE
		chmod a+w /srv/tftp/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/} < /dev/tty
		if [ "$(tail -n +0 /srv/tftp/$DESTFILE|md5sum)" != "$(tail -n +0 $THISDIR/backups/$sw.txt|md5sum)" ] && [ -s /srv/tftp/$DESTFILE ]; then
			mv /srv/tftp/$DESTFILE $THISDIR/backups/$sw.txt
			chmod go-w $THISDIR/backups/$sw.txt
			git add $THISDIR/backups/$sw.txt
		else
			rm /srv/tftp/$DESTFILE
		fi
		;;
	*)
		echo "Don't know how to handle class: $class for $sw"
		;;
esac
done
git commit -a -m "Auto backup commit $(date) on $(uname -n)"
git push
