#!/bin/bash -x
DATADIR=/etc/switches
SWITCHLIST=$DATADIR/switches.txt
BACKUPDIR=$DATADIR/backups
TFTPDIR=/srv/tftp
THISDIR=$PWD
function git() {
	pushd $DATADIR
	/usr/bin/git "$@"
	popd
}
git pull
SEARCH=""
if [ -n "$1" ]; then
	SEARCH="/$1/ "
fi
awk "$SEARCH"'{ print $1,$4,$5,$6 }' < $SWITCHLIST | while read sw ip class password;do
MYIP="$(ip ro get $ip|awk '/src/ { print $5 }')"
echo name: $sw ip: $ip myip: $MYIP class: $class
case "$class" in
	gs748tv5)
		class=gs724tv4
		;;
esac
case "$class" in
	gs108tv3|gs308tv1)
		mkdir -p $TFTPDIR
		DESTFILE=$sw.txt
		touch $TFTPDIR/$DESTFILE
		chmod a+w $TFTPDIR/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/}
		if [ "$(tail -n +10 $TFTPDIR/$DESTFILE|md5sum)" != "$(tail -n +10 $BACKUPDIR/$sw.txt|md5sum)" ] && [ -s $TFTPDIR/$DESTFILE ]; then
			mv $TFTPDIR/$DESTFILE $BACKUPDIR/$sw.txt
			chmod go-w $BACKUPDIR/$sw.txt
			git add $BACKUPDIR/$sw.txt
		else
			rm $TFTPDIR/$DESTFILE
		fi
		;;
	gs724tv4)
		mkdir -p $TFTPDIR/backup
		DESTFILE=backup/$sw.txt
		touch $TFTPDIR/$DESTFILE
		chmod a+w $TFTPDIR/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/}
		if [ "$(tail -n +10 $TFTPDIR/$DESTFILE|md5sum)" != "$(tail -n +10 $BACKUPDIR/$sw.txt|md5sum)" ] && [ -s $TFTPDIR/$DESTFILE ]; then
			mv $TFTPDIR/$DESTFILE $BACKUPDIR/$sw.txt
			chmod go-w $BACKUPDIR/$sw.txt
			git add $BACKUPDIR/$sw.txt
		else
			rm $TFTPDIR/$DESTFILE
		fi
		;;
	sx200)
		echo Skipping $sw as it has no CLI
		;;
	sx300)
		mkdir -p $TFTPDIR/backup
		DESTFILE=backup/$sw.txt
		touch $TFTPDIR/$DESTFILE
		chmod a+w $TFTPDIR/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/}
		if [ "$(tail -n +0 $TFTPDIR/$DESTFILE|md5sum)" != "$(tail -n +0 $BACKUPDIR/$sw.txt|md5sum)" ] && [ -s $TFTPDIR/$DESTFILE ]; then
			mv $TFTPDIR/$DESTFILE $BACKUPDIR/$sw.txt
			chmod go-w $BACKUPDIR/$sw.txt
			git add $BACKUPDIR/$sw.txt
		else
			rm $TFTPDIR/$DESTFILE
		fi
		;;
	hp2530|hp2520-S15|hp2620)
		mkdir -p $TFTPDIR/backup
		DESTFILE=backup/$sw.txt
		touch $TFTPDIR/$DESTFILE
		chmod a+w $TFTPDIR/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/}
		if [ "$(tail -n +0 $TFTPDIR/$DESTFILE|md5sum)" != "$(tail -n +0 $BACKUPDIR/$sw.txt|md5sum)" ] && [ -s $TFTPDIR/$DESTFILE ]; then
			mv $TFTPDIR/$DESTFILE $BACKUPDIR/$sw.txt
			chmod go-w $BACKUPDIR/$sw.txt
			git add $BACKUPDIR/$sw.txt
		else
			rm $TFTPDIR/$DESTFILE
		fi
		;;
	lgs318p)
		mkdir -p $TFTPDIR/backup
		DESTFILE=backup/$sw.txt
		touch $TFTPDIR/$DESTFILE
		chmod a+w $TFTPDIR/$DESTFILE
		$THISDIR/expect/$class $ip $sw $MYIP ${password/:*/} ${password/*:/} < /dev/tty
		if [ "$(tail -n +0 $TFTPDIR/$DESTFILE|md5sum)" != "$(tail -n +0 $BACKUPDIR/$sw.txt|md5sum)" ] && [ -s $TFTPDIR/$DESTFILE ]; then
			mv $TFTPDIR/$DESTFILE $BACKUPDIR/$sw.txt
			chmod go-w $BACKUPDIR/$sw.txt
			git add $BACKUPDIR/$sw.txt
		else
			rm $TFTPDIR/$DESTFILE
		fi
		;;
	*)
		echo "Don't know how to handle class: $class for $sw"
		;;
esac
done
git commit -a -m "Auto backup commit $(date) on $(uname -n)"
git push
