#!/usr/bin/expect
set ip [lindex $argv 0]
set switch [lindex $argv 1]
set tftpserver [lindex $argv 2]
set user [lindex $argv 3]
set password [lindex $argv 4]

set timeout 20

spawn -noecho ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no $user@$ip
expect_after eof {exit 0}
expect "password:" { send "$password\r" }
expect ">"
send "enable\r"
expect "#"
send "copy nvram:startup-config tftp://$tftpserver/backup/$switch.txt\r"
expect "Mode"
expect "Path"
expect "Filename"
expect "Data"
expect "Are you sure you want to start? (y/n)"
send "y\r"
expect "File transfer operation completed successfully."
expect "#"
send "quit\r"
expect "\n"
