#!/usr/bin/expect -f
set ip [lindex $argv 0]
set switch [lindex $argv 1]
set tftpserver [lindex $argv 2]
set user [lindex $argv 3]
set password [lindex $argv 4]

set timeout 20

spawn -noecho ssh $user@$ip
expect_after eof {exit 0}
expect "Password:" { send "$password\r" }
expect {#} { interact }
